spring.application.name=awschallenge
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${RDS_URL}
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}
spring.datasource.driver-class-name=${RDS_DRIVER:org.postgresql.Driver}
spring.jpa.database-platform=${RDS_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${RDS_DDL_AUTO:update}
#Debug mode
logging.level.root=INFO